# Generated by Django 5.0.6 on 2024-06-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regin', '0006_alter_video_time_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Langauge', models.CharField(max_length=100)),
            ],
        ),
    ]
