# Generated by Django 5.0.6 on 2024-06-18 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regin', '0007_langauge'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='langauge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regin.langauge'),
        ),
    ]
