# Generated by Django 5.0.6 on 2024-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regin', '0008_course_langauge'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Deadline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
